SELECT *
FROM Class
ORDER
BY cid DESC

SELECT *
FROM [Object]
ORDER BY OID DESC


UPDATE [Object] SET EDes = '{}' WHERE [Type] = 2

SELECT *
FROM Account
SELECT *
FROM Member

DELETE FROM Account WHERE MID = 653
DELETE FROM member WHERE MID = 653
DELETE FROM [Object] WHERE [OID] = 653